config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "movies#index"

  resources :movies do
    resources :reviews
    resources :favorites
  end

  resources :genres

  resource :session, only: [:new, :create, :destroy]
  get "login" => "sessions#new"

  resources :users
  get "signup" => "users#new"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; <%= Time.now.year %>
    <%= link_to "The Pragmatic Studio", "https://pragmaticstudio.com" %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
      <li>
        <%= link_to "Released Movies", movies_path %>
      </li>
      <li>
        <%= link_to "Upcoming Movies", filtered_movies_path(:upcoming) %>
      </li>
      <li>
        <%= link_to "Recent Movies", filtered_movies_path(:recent) %>
      </li>
      <li>
        <%= link_to "Hits", filtered_movies_path(:hits) %>
      </li>
      <li>
        <%= link_to "Flops", filtered_movies_path(:flops) %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Account Settings", edit_user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path, data: { turbo_method: :delete }, class: "button"  %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", login_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Signup", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>